# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Empowerment
    url: '#empowerment'
    weight: 10
  - name: News
    url: '#news'
    identifier: news
    weight: 20
  - name: Kooperationen
    url: '/kooperation'
    weight: 30
  - name: Angebote
    url: '/angebote'
    weight: 40
  - name: Events
    url: '/event'
    weight: 50
  - name: Blog
    url: '/post'
    weight: 60
  - name: Verein
    url: /
    identifier: verein
    weight: 70
  - name: Mitglied werden
    parent: verein
    url: https://easyverein.com/public/Epipower/applicationform/6424
    weight: 10
  - name: Satzung
    parent: verein
    url: uploads/Satzung_03_23.pdf
    weight: 20
  - name: Finanzierung
    parent: verein
    url: '/verein/finanzierung'
    weight: 30
  - name: Team
    parent: verein
    url: '#team'
    weight: 40
  - name: Kontakt
    parent: verein
    url: '#contact'
    weight: 50
  




  # - name: Projekte
  #   url: '/project'
    #  weight: 50

  #     - name: Projekte
  #   parent: news
  #   url: '/project'
  #   weight: 10
  # - name: Events
  #   parent: news
  #   url: '/event'
  #   weight: 20
  # - name: Blog
  #   parent: news
  #   url: '/post'
  #   weight: 30
# main:
#   - name: Home
#     url: /
#     weight: 10
#   - name: Tags
#     identifier: tags
#     weight: 20
#   - name: Academic
#     parent: tags
#     url: tags/academic/
#     weight: 10